# Generated by Django 5.1.5 on 2025-02-08 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_deliveryagent_saler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('delivery_agent', 'Delivery Agent'), ('saler', 'Saler')], default='user', max_length=50),
        ),
        migrations.RemoveField(
            model_name='saler',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='saler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pages.user'),
        ),
        migrations.DeleteModel(
            name='DeliveryAgent',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Saler',
        ),
    ]
