# Generated by Django 5.1.5 on 2025-02-10 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_user_role_remove_saler_user_product_saler_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryassignment',
            options={'verbose_name': 'تعيين التوصيل', 'verbose_name_plural': 'تعيينات التوصيل'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'طلب', 'verbose_name_plural': 'طلبات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-rating'], 'verbose_name': 'منتج', 'verbose_name_plural': 'منتجات'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'تقرير', 'verbose_name_plural': 'تقارير'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterField(
            model_name='order',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pages.user', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='DeliveryAgent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='pages.user', verbose_name='وكيل التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Quantity',
            field=models.IntegerField(default=1, verbose_name='كمية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='products/', verbose_name='صورة المنتج'),
        ),
        migrations.AlterField(
            model_name='report',
            name='GeneratedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pages.user', verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ReportData',
            field=models.TextField(verbose_name='بيانات التقرير'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ReportType',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Inventory', 'Inventory'), ('Financial', 'Financial')], max_length=20, verbose_name='نوع التقرير'),
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product')),
            ],
            options={
                'verbose_name': 'فلاش سيل',
                'verbose_name_plural': 'فلاش سيلات',
                'ordering': ['-rating'],
            },
        ),
    ]
