# Generated by Django 5.1.5 on 2025-02-10 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_deliveryassignment_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashsale',
            options={'verbose_name': 'فلاش سيل', 'verbose_name_plural': 'فلاش سيلات'},
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='rating',
        ),
    ]
