# Generated by Django 5.1.5 on 2025-02-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_flashsale_options_remove_flashsale_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=90, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashsale',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=2),
            preserve_default=False,
        ),
    ]
