# Generated by Django 5.1.5 on 2025-02-12 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_category_alter_user_managers_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
