# Generated by Django 5.1.5 on 2025-02-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('orangered', 'OrangeRed'), ('black', 'Black')], default='red', max_length=50, verbose_name='اللون'),
        ),
    ]
